# Generated by Django 5.0.1 on 2024-01-25 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=1)),
                ('phone', models.IntegerField(default=1)),
                ('email', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_persons', models.IntegerField(default=1)),
                ('since', models.DateField(verbose_name='date published')),
                ('until', models.DateField(verbose_name='date published')),
                ('status', models.CharField(choices=[('not_paid', 'Order is not paid'), ('ordered', 'Order completed'), ('reservation', 'Apartment is reserved')], max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.customers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=30)),
                ('rooms', models.IntegerField(default=1)),
                ('beds', models.IntegerField(default=1)),
                ('property', models.CharField(max_length=30)),
                ('room_turnover', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.owners')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.customers')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.owners')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default=None, max_length=30)),
                ('price', models.IntegerField(default=50)),
                ('description', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartment.owners')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='questbook',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='questbook',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartment.customers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.rooms'),
        ),
        migrations.AddField(
            model_name='sales',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.services'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
