# Generated by Django 5.0.1 on 2024-01-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_customers_orders_owners_rooms_sales_services_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Owners',
            new_name='Owner',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
