# Generated by Django 5.0.1 on 2024-01-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_rename_customers_customer_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_turnover',
        ),
    ]
