# Generated by Django 5.0.1 on 2024-01-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_remove_room_room_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='', upload_to='static/css/images/'),
        ),
    ]
