# Generated by Django 5.0.1 on 2024-02-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartment.room'),
        ),
        migrations.AlterField(
            model_name='order',
            name='since',
            field=models.DateField(verbose_name='since'),
        ),
        migrations.AlterField(
            model_name='order',
            name='until',
            field=models.DateField(verbose_name='till'),
        ),
    ]
