# Generated by Django 5.0.1 on 2024-02-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('reserved', 'Room is reserved, not payed'), ('ordered', 'Order is completed')], default=None, max_length=30),
        ),
    ]
