# Generated by Django 5.0.1 on 2024-02-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_remove_event_title_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
