# Generated by Django 5.0.1 on 2024-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('reserved', 'Room is reserved, not payed'), ('ordered', 'Order is completed')], default='order', max_length=30),
        ),
    ]
