# Generated by Django 5.0.1 on 2024-02-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_remove_event_title_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartment.customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='number_persons',
            field=models.IntegerField(default=1),
        ),
    ]
